local corex_path = os.getenv("COREX_PATH") or os.getenv("CUDA_PATH") or "/usr/local/corex"

target("llaisys-device-iluvatar")
    set_kind("static")
    set_languages("cxx17")
    add_defines("ENABLE_ILUVATAR_API")
    set_toolset("cxx", corex_path .. "/bin/clang++")
    add_files("../src/device/iluvatar/iluvatar_runtime_api.cpp")
    add_includedirs("../include", corex_path .. "/include")
    add_linkdirs(corex_path .. "/lib64")
    add_syslinks("cudart")
    add_cxflags("-x", "ivcore", "--cuda-path=" .. corex_path, "-fPIC", "-fno-gpu-rdc", {force = true})
    on_install(function (target) end)
target_end()

target("llaisys-ops-iluvatar")
    set_kind("static")
    add_deps("llaisys-tensor")
    set_languages("cxx17")
    add_defines("ENABLE_ILUVATAR_API")
    set_toolset("cxx", corex_path .. "/bin/clang++")
    add_files("../src/ops/iluvatar/iluvatar_ops.cpp")
    add_includedirs("../include", corex_path .. "/include")
    add_linkdirs(corex_path .. "/lib64")
    add_syslinks("cudart")
    add_cxflags("-x", "ivcore", "--cuda-path=" .. corex_path, "-fPIC", "-fno-gpu-rdc", {force = true})
    on_install(function (target) end)
target_end()
