local corex_path = os.getenv("COREX_PATH") or os.getenv("CUDA_PATH") or "/usr/local/corex"

rule("iluvatar.cuda")
    set_sourcekinds("cu")
    add_deps("utils.inherit.links")
    on_build_files("private.action.build.object", {jobgraph = true, batch = true})

target("llaisys-device-iluvatar")
    set_kind("static")
    add_rules("iluvatar.cuda")
    set_languages("cxx17")
    add_defines("ENABLE_ILUVATAR_API")
    set_toolset("cu", corex_path .. "/bin/clang++")
    add_files("../src/device/iluvatar/*.cu")
    add_includedirs("../include", corex_path .. "/include")
    add_linkdirs(corex_path .. "/lib64")
    add_syslinks("cudart")
    add_cuflags("-x", "ivcore", "--cuda-path=" .. corex_path, "-fPIC", "-fno-gpu-rdc", "-std=c++17", {force = true})
    on_install(function (target) end)
target_end()

target("llaisys-ops-iluvatar")
    set_kind("static")
    add_deps("llaisys-tensor")
    add_rules("iluvatar.cuda")
    set_languages("cxx17")
    add_defines("ENABLE_ILUVATAR_API")
    set_toolset("cu", corex_path .. "/bin/clang++")
    add_files("../src/ops/nvidia/*.cu")
    add_includedirs("../include", corex_path .. "/include")
    add_linkdirs(corex_path .. "/lib64")
    add_syslinks("cudart")
    add_cuflags("-x", "ivcore", "--cuda-path=" .. corex_path, "-fPIC", "-fno-gpu-rdc", "-std=c++17", {force = true})
    on_install(function (target) end)
target_end()
