[metadata]
name = llaisys
version = 0.1.0
description = Python bindings for the LLAISYS assignment runtime
author = Pan Zezhong
license = MIT

[options]
packages = find:
include_package_data = True
zip_safe = False
python_requires = >=3.9
install_requires =
    accelerate
    ml_dtypes>=0.5.0
    safetensors>=0.4.1
    torch>=2.4.0
    transformers

[options.package_data]
llaisys =
    libllaisys/*.dll
    libllaisys/*.dylib
    libllaisys/*.so
